/** pm2 process file for SpikeScope on the research VPS. */
module.exports = {
  apps: [
    {
      name: "spikescope",
      cwd: "/opt/spikescope/server",
      script: "dist/index.js",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
        PORT: "8788",
        DERIV_POLL_MS: "3000",
        DERIV_HISTORY_TICKS: "15000",
        COST_PCT_ROUND_TRIP: "0.02",
        KILL_MIN_SAMPLES: "50",
        KILL_MIN_WR: "0.45",
        KILL_MIN_EXPECTANCY: "0",
        // Predictor mode: only signal learned edge pockets; wide stops
        PREDICTOR_MODE: "1",
        PAPER_LEARN_MAX: "0",
        PATTERN_TRADE_MIN: "0.55",
        PAPER_COOLDOWN_MS: "90000",
        PAPER_MAX_PENDING: "1",
        SPIKE_WATCH_AGE_RATIO: "0.4",
        ENTRY_MIN_CONF: "0.2",
        ENTRY_MIN_P500: "0.12",
        ENTRY_MIN_AGE_RATIO: "0.4",
        ENTRY_MAX_STOP_PCT: "4",
        ENTRY_HARD_REGIME: "0",
        ENTRY_HARD_FOCUS: "0",
        POLICY_MIN_CROSS_N: "12",
        POLICY_MIN_AGE_N: "40",
        POLICY_MIN_CROSS_EXP: "0",
        POLICY_MIN_AGE_EXP: "0",
        LEVEL_STOP_FLOOR_PCT: "0.15",
        LEVEL_TARGET_FLOOR_PCT: "0.12",
        FOCUS_MIN_N: "8",
        LEVEL_TUNE_MIN_N: "8",
        WALK_FORWARD_HOLDOUT: "0.2",
        VOL_CANDLE_SEC: "60",
        VOL_MIN_HOLD_TICKS: "180",
        VOL_HORIZON_TICKS: "900",
        VOL_ENTRY_MIN_CONF: "0.32",
        VOL_SCORE_THRESHOLD: "1.25",
        VOL_STOP_ATR: "1.85",
        VOL_TARGET_ATR: "2.6",
        VOL_PAPER_COOLDOWN_MS: "120000",
        VOL_PAPER_MAX_PENDING: "1",
      },
    },
  ],
};
